### ISSUE TITLE
Sine parsing algorithm theory

### ISSUE THREAD

**Issue by modulovalue** [pschiffmann/sine-parser#1]
Hello @pschiffmann,

I was wondering if you remember what theory your parser here has been based on?

It's obviously an LR parser, and you seem to implement some form of lookahead. I've tried looking for papers that refer to some `sine` parsing algorithm, but unfortunately I couldn't find much not related to the `sin` function.

I know that this repo is old and you've probably moved on, but if you remember anything, It would be really helpful if you could share some of it. If not, no problem!

**Comment by pschiffmann** [comment]
Hey! Sorry for the late response, and also sorry for misleading you with that repo. You can't find papers on sine parsing because it was invented by me – when I was a 3rd semester bachelor student. From a scientific point of view, this is unverified garbage ;)
IIRC I tried to encode LR parser tables in a different format. I wanted to introduce additional actions (other than shift and reduce). The goal was to accept the full LR grammar set, but have a more intuitive/human readable table. Or it should generate better error messages. Or something like that. Look, I was just barely starting my scientific carrier. :D

**Comment by modulovalue** [comment]
I see. Thank you for the response @pschiffmann!
